# Generated by Django 5.0.4 on 2024-05-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(max_length=1024)),
                ("hostname", models.CharField(max_length=256)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_time", models.IntegerField(null=True)),
                ("is_up", models.BooleanField()),
                ("time", models.DateTimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
        ),
    ]
